package com.ravi.blissbud.ui.theme

import androidx.compose.ui.graphics.Color

object AppColorScheme{
        object Dark{
            val PRIMARY = Color(0xFFA6C8FF)
            val ON_PRIMARY = Color(0xFF003060)
            val PRIMARY_CONTAINER = Color(0xFF004787)
            val ON_PRIMARY_CONTAINER = Color(0xFFD5E3FF)
            val SECONDARY = Color(0xFFA6C8FF)
            val ON_SECONDARY = Color(0xFF003060)
            val SECONDARY_CONTAINER = Color(0xFF004787)
            val ON_SECONDARY_CONTAINER = Color(0xFFD5E3FF)
            val TERTIARY = Color(0xFFA6C8FF)
            val ON_TERTIARY = Color(0xFF003060)
            val TERTIARY_CONTAINER = Color(0xFF004787)
            val ON_TERTIARY_CONTAINER = Color(0xFFD5E3FF)
            val ERROR = Color(0xFFFFB4AB)
            val ON_ERROR = Color(0xFF690005)
            val ERROR_CONTAINER = Color(0xFF93000A)
            val ON_ERROR_CONTAINER = Color(0xFFFFDAD6)
            val BACKGROUND = Color(0xFF1A1C1E)
            val ON_BACKGROUND = Color(0xFFE3E2E6)
            val SURFACE = Color(0xFF1A1C1E)
            val ON_SURFACE = Color(0xFFE3E2E6)
            val SURFACE_VARIANT = Color(0xFF43474E)
            val ON_SURFACE_VARIANT = Color(0xFFC4C6CF)
            val OUTLINE = Color(0xFF8D9199)
            val INVERSE_ON_SURFACE = Color(0xFF1A1C1E)
            val INVERSE_SURFACE = Color(0xFFE3E2E6)
            val INVERSE_PRIMARY = Color(0xFF225FA6)
            val SURFACE_TINT = Color(0xFFA6C8FF)
        }
        object Light{
            val PRIMARY = Color(0xFF225FA6)
            val ON_PRIMARY = Color(0xFFFFFFFF)
            val PRIMARY_CONTAINER = Color(0xFFD5E3FF)
            val ON_PRIMARY_CONTAINER = Color(0xFF001C3B)
            val SECONDARY = Color(0xFF225FA6)
            val ON_SECONDARY = Color(0xFFFFFFFF)
            val SECONDARY_CONTAINER = Color(0xFFD5E3FF)
            val ON_SECONDARY_CONTAINER = Color(0xFF001C3B)
            val TERTIARY = Color(0xFF225FA6)
            val ON_TERTIARY = Color(0xFFFFFFFF)
            val TERTIARY_CONTAINER = Color(0xFFD5E3FF)
            val ON_TERTIARY_CONTAINER = Color(0xFF001C3B)
            val ERROR = Color(0xFFBA1A1A)
            val ON_ERROR = Color(0xFFFFDAD6)
            val ERROR_CONTAINER = Color(0xFFFFFFFF)
            val ON_ERROR_CONTAINER = Color(0xFF410002)
            val BACKGROUND = Color(0xFFFDFBFF)
            val ON_BACKGROUND = Color(0xFF1A1C1E)
            val SURFACE = Color(0xFFFDFBFF)
            val ON_SURFACE = Color(0xFF1A1C1E)
            val SURFACE_VARIANT = Color(0xFFE0E2EC)
            val ON_SURFACE_VARIANT = Color(0xFF43474E)
            val OUTLINE = Color(0xFF74777F)
            val INVERSE_ON_SURFACE = Color(0xFFF1F0F4)
            val INVERSE_SURFACE = Color(0xFF2F3033)
            val INVERSE_PRIMARY = Color(0xFFA6C8FF)
            val SURFACE_TINT = Color(0xFF225FA6)
        }
}